### PR TITLE
Add missed 'jpeg' extension

### PR DESCRIPTION
**Pull request by Bihaqo**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by colesbury** [comment]
Thanks, I can merge this once you complete the CLA

**Comment by Bihaqo** [comment]
Actually, I did complete it, I don't know why it says I didn't.
screen shot 2016-07-12 at 18 41 28

**Comment by colesbury** [comment]
Thanks!

**Pull request merged**
